import { createHash } from "node:crypto";
import { Prisma, type FinancialObligation, type ObligationPayment } from "@prisma/client";
import type { RequestContext } from "../middleware/requestContext.js";
import { prisma } from "../lib/prisma.js";
import { FinanceError } from "./expenseService.js";
import { presentDistribution } from "./distributionService.js";

export type ObligationCancelInput = { reason: string };
export type PaymentReverseInput = { reason: string };
function fail(status: number, code: string, message: string): never { throw new FinanceError(status, code, message); }
function mutateWorkspace(ctx: RequestContext) { if (!ctx.activeWorkspaceId || (ctx.membershipRole !== "owner" && ctx.membershipRole !== "admin")) fail(403, "FINANCE_FORBIDDEN", "Você não possui permissão para operar obrigações."); return ctx.activeWorkspaceId; }
function readScope(ctx: RequestContext) { if (!ctx.activeWorkspaceId) fail(403, "FINANCE_FORBIDDEN", "Workspace ativo não definido."); if (ctx.membershipRole === "owner" || ctx.membershipRole === "admin") return { workspaceId: ctx.activeWorkspaceId, personId: undefined }; if (ctx.membershipRole === "technician" && ctx.technicianPersonId) return { workspaceId: ctx.activeWorkspaceId, personId: ctx.technicianPersonId }; fail(403, "FINANCE_FORBIDDEN", "Você não possui permissão para consultar obrigações."); }
function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
async function replay(tx: Prisma.TransactionClient, workspaceId: string, actorUserId: string, action: string, key: string, requestHash: string) {
  const record = await tx.financeIdempotency.findUnique({ where: { workspaceId_actorUserId_actionNamespace_idempotencyKey: { workspaceId, actorUserId, actionNamespace: action, idempotencyKey: key } } });
  if (!record) return null; if (record.requestHash !== requestHash) fail(409, "IDEMPOTENCY_KEY_REUSED", "Chave de idempotência reutilizada com outra solicitação.");
  const obligation = await tx.financialObligation.findFirst({ where: { id: record.resourceId, workspaceId } }); if (!obligation) fail(409, "IDEMPOTENCY_RESOURCE_MISSING", "Materialização idempotente não encontrada."); return obligation;
}
async function obligationDistribution(tx: Prisma.TransactionClient, obligation: FinancialObligation) { const distribution = await tx.distribution.findFirst({ where: { id: obligation.distributionId, workspaceId: obligation.workspaceId } }); if (!distribution) fail(409, "OBLIGATION_DISTRIBUTION_MISSING", "Distribuição vinculada não encontrada."); return distribution; }
export function presentPayment(payment: ObligationPayment) { return { id: payment.id, obligationId: payment.obligationId, amount: payment.amount.toFixed(2), currencyCode: payment.currencyCode, status: payment.status, paidAt: payment.paidAt.toISOString(), paidByUserId: payment.paidByUserId, reversedAt: payment.reversedAt?.toISOString() ?? null, reversedByUserId: payment.reversedByUserId ?? null, reversalReason: payment.reversalReason ?? null }; }
export function presentObligation(obligation: FinancialObligation, distribution: Awaited<ReturnType<typeof obligationDistribution>>, payment?: ObligationPayment | null) { return { id: obligation.id, distributionId: obligation.distributionId, distribution: presentDistribution(distribution), amount: obligation.amount.toFixed(2), currencyCode: obligation.currencyCode, status: obligation.status, createdAt: obligation.createdAt.toISOString(), createdByUserId: obligation.createdByUserId, paidAt: obligation.paidAt?.toISOString() ?? null, paidByUserId: obligation.paidByUserId ?? null, cancelledAt: obligation.cancelledAt?.toISOString() ?? null, cancelledByUserId: obligation.cancelledByUserId ?? null, cancellationReason: obligation.cancellationReason ?? null, reversedAt: obligation.reversedAt?.toISOString() ?? null, reversedByUserId: obligation.reversedByUserId ?? null, reversalReason: obligation.reversalReason ?? null, payment: payment ? presentPayment(payment) : null }; }
async function enriched(tx: Prisma.TransactionClient, obligation: FinancialObligation) { const [distribution, payment] = await Promise.all([obligationDistribution(tx, obligation), tx.obligationPayment.findFirst({ where: { obligationId: obligation.id, workspaceId: obligation.workspaceId } })]); return { obligation, distribution, payment }; }
export async function createObligation(ctx: RequestContext, distributionId: string, key: string) { const workspaceId = mutateWorkspace(ctx), requestHash = hash({ distributionId }); try { return await prisma.$transaction(async tx => { const seen = await replay(tx, workspaceId, ctx.actorUserId, "obligation.create", key, requestHash); if (seen) return { ...await enriched(tx, seen), idempotent: true }; const distribution = await tx.distribution.findFirst({ where: { id: distributionId, workspaceId } }); if (!distribution) fail(404, "DISTRIBUTION_NOT_FOUND", "Distribuição não encontrada."); if (distribution.status !== "active") fail(422, "DISTRIBUTION_NOT_ELIGIBLE", "Distribuição não está ativa."); const obligation = await tx.financialObligation.create({ data: { workspaceId, distributionId, amount: distribution.resolvedAmount, currencyCode: distribution.currencyCode, createdByUserId: ctx.actorUserId } }); await tx.financeIdempotency.create({ data: { workspaceId, actorUserId: ctx.actorUserId, actionNamespace: "obligation.create", idempotencyKey: key, requestHash, resourceType: "obligation", resourceId: obligation.id } }); return { obligation, distribution, payment: null, idempotent: false }; }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") { const seen = await prisma.$transaction(tx => replay(tx, workspaceId, ctx.actorUserId, "obligation.create", key, requestHash)); if (seen) return { ...await prisma.$transaction(tx => enriched(tx, seen)), idempotent: true }; fail(409, "OBLIGATION_ALREADY_EXISTS", "Já existe obrigação para esta distribuição."); } throw error; } }
async function readable(ctx: RequestContext, id?: string) { const scope = readScope(ctx); const distributions = scope.personId ? await prisma.distribution.findMany({ where: { workspaceId: scope.workspaceId, participantPersonId: scope.personId }, select: { id: true } }) : undefined; const obligations = await prisma.financialObligation.findMany({ where: { workspaceId: scope.workspaceId, ...(id ? { id } : {}), ...(distributions ? { distributionId: { in: distributions.map(d => d.id) } } : {}) }, orderBy: [{ createdAt: "desc" }, { id: "asc" }] }); if (id && !obligations[0]) fail(404, "OBLIGATION_NOT_FOUND", "Obrigação não encontrada."); return prisma.$transaction(tx => Promise.all(obligations.map(o => enriched(tx, o)))); }
export async function listObligations(ctx: RequestContext) { return readable(ctx); }
export async function getObligation(ctx: RequestContext, id: string) { return (await readable(ctx, id))[0]; }
async function change(ctx: RequestContext, id: string, key: string, action: string, requestHash: string, operation: (tx: Prisma.TransactionClient, current: FinancialObligation) => Promise<FinancialObligation>) {
  const workspaceId = mutateWorkspace(ctx);
  try {
    return await prisma.$transaction(async tx => {
      const seen = await replay(tx, workspaceId, ctx.actorUserId, action, key, requestHash);
      if (seen) return { ...await enriched(tx, seen), idempotent: true };
      const current = await tx.financialObligation.findFirst({ where: { id, workspaceId } });
      if (!current) fail(404, "OBLIGATION_NOT_FOUND", "Obrigação não encontrada.");
      try {
        const obligation = await operation(tx, current);
        await tx.financeIdempotency.create({ data: { workspaceId, actorUserId: ctx.actorUserId, actionNamespace: action, idempotencyKey: key, requestHash, resourceType: "obligation", resourceId: obligation.id } });
        return { ...await enriched(tx, obligation), idempotent: false };
      } catch (opError) {
        const raced = await replay(tx, workspaceId, ctx.actorUserId, action, key, requestHash);
        if (raced) return { ...await enriched(tx, raced), idempotent: true };
        throw opError;
      }
    });
  } catch (error) {
    const seen = await prisma.$transaction(tx => replay(tx, workspaceId, ctx.actorUserId, action, key, requestHash));
    if (seen) return { ...await prisma.$transaction(tx => enriched(tx, seen)), idempotent: true };
    throw error;
  }
}
export async function cancelObligation(ctx: RequestContext, id: string, input: ObligationCancelInput, key: string) { return change(ctx, id, key, "obligation.cancel", hash({ id, reason: input.reason.trim() }), async (tx, current) => { if (current.status === "paid") fail(409, "OBLIGATION_ALREADY_SETTLED", "Obrigação já foi liquidada."); if (current.status !== "pending") fail(409, "OBLIGATION_NOT_CANCELLABLE", "Obrigação não pode ser cancelada."); const update = await tx.financialObligation.updateMany({ where: { id, workspaceId: current.workspaceId, status: "pending" }, data: { status: "cancelled", cancelledAt: new Date(), cancelledByUserId: ctx.actorUserId, cancellationReason: input.reason.trim() } }); if (update.count !== 1) fail(409, "OBLIGATION_NOT_CANCELLABLE", "Obrigação não pode ser cancelada."); return tx.financialObligation.findUniqueOrThrow({ where: { id } }); }); }
export async function settleObligation(ctx: RequestContext, id: string, key: string) { return change(ctx, id, key, "obligation.settle", hash({ id }), async (tx, current) => { if (current.status !== "pending") fail(409, "OBLIGATION_NOT_SETTLEABLE", "Obrigação não pode ser liquidada."); const update = await tx.financialObligation.updateMany({ where: { id, workspaceId: current.workspaceId, status: "pending" }, data: { status: "paid", paidAt: new Date(), paidByUserId: ctx.actorUserId } }); if (update.count !== 1) fail(409, "OBLIGATION_NOT_SETTLEABLE", "Obrigação não pode ser liquidada."); await tx.obligationPayment.create({ data: { workspaceId: current.workspaceId, obligationId: current.id, amount: current.amount, currencyCode: current.currencyCode, paidAt: new Date(), paidByUserId: ctx.actorUserId } }); return tx.financialObligation.findUniqueOrThrow({ where: { id } }); }); }
export async function reversePayment(ctx: RequestContext, obligationId: string, paymentId: string, input: PaymentReverseInput, key: string) { const workspaceId = mutateWorkspace(ctx), requestHash = hash({ obligationId, paymentId, reason: input.reason.trim() }); return change(ctx, obligationId, key, "obligation.payment.reverse", requestHash, async (tx, current) => { const payment = await tx.obligationPayment.findFirst({ where: { id: paymentId, obligationId, workspaceId } }); if (!payment) fail(404, "OBLIGATION_PAYMENT_NOT_FOUND", "Pagamento não encontrado."); if (current.status !== "paid" || payment.status !== "effective") fail(409, "OBLIGATION_PAYMENT_NOT_REVERSIBLE", "Pagamento não pode ser revertido."); const now = new Date(); const changed = await tx.obligationPayment.updateMany({ where: { id: paymentId, workspaceId, status: "effective" }, data: { status: "reversed", reversedAt: now, reversedByUserId: ctx.actorUserId, reversalReason: input.reason.trim() } }); if (changed.count !== 1) fail(409, "OBLIGATION_PAYMENT_NOT_REVERSIBLE", "Pagamento não pode ser revertido."); await tx.financialObligation.update({ where: { id: obligationId }, data: { status: "reversed", reversedAt: now, reversedByUserId: ctx.actorUserId, reversalReason: input.reason.trim() } }); return tx.financialObligation.findUniqueOrThrow({ where: { id: obligationId } }); }); }
